import type { CubeDefinition, OutputModality, PresetChain } from "./schema.js";

export const CUBE_DEFINITIONS: CubeDefinition[] = [
  {
    schema: 1,
    id: "identity/london",
    label: "London",
    category: "identity",
    role: "place",
    colorAccent: "#E63946",
    capabilities: ["place"],
    metadata: { lat: 51.5074, lon: -0.1278, city: "London", timezone: "Europe/London" },
    registers: [],
    topics: { publish: ["place/name"], subscribe: [] },
    description: "Use weather and data for London, UK",
  },
  {
    schema: 1,
    id: "identity/foundry",
    label: "Foundry",
    category: "identity",
    role: "place",
    colorAccent: "#6E5494",
    capabilities: ["place", "repo"],
    metadata: { city: "Foundry" },
    registers: [],
    topics: { publish: ["place/name"], subscribe: [] },
    description: "Scope GitHub activity to this project",
  },
  {
    schema: 1,
    id: "identity/tokyo",
    label: "Tokyo",
    category: "identity",
    role: "place",
    colorAccent: "#FF6B6B",
    capabilities: ["place"],
    metadata: { lat: 35.6762, lon: 139.6503, city: "Tokyo", timezone: "Asia/Tokyo" },
    registers: [],
    topics: { publish: ["place/name"], subscribe: [] },
    description: "Use weather and data for Tokyo, Japan",
  },
  {
    schema: 1,
    id: "identity/weather",
    label: "Weather",
    category: "identity",
    role: "source",
    colorAccent: "#457B9D",
    capabilities: ["weather"],
    registers: [],
    topics: { publish: ["weather/temp", "weather/rain"], subscribe: [] },
    description: "Fetch temperature and rain from the sky",
  },
  {
    schema: 1,
    id: "source/time",
    label: "Time",
    category: "identity",
    role: "transform",
    colorAccent: "#5C6BC0",
    capabilities: ["time"],
    registers: [],
    topics: { publish: ["time/hour"], subscribe: [] },
    description: "Formats time for places immediately before it in the chain",
  },
  {
    schema: 1,
    id: "modifier/calm",
    label: "Calm",
    category: "identity",
    role: "modifier",
    colorAccent: "#2A9D8F",
    capabilities: ["smooth"],
    registers: [],
    topics: {
      publish: ["weather/rain/smoothed"],
      subscribe: ["weather/rain"],
    },
    description: "Smooth signals for gentle ambient output",
  },
  {
    schema: 1,
    id: "modifier/random",
    label: "Random",
    category: "identity",
    role: "modifier",
    colorAccent: "#9B59B6",
    capabilities: ["random"],
    registers: [],
    topics: { publish: ["modifier/random"], subscribe: [] },
    description: "Add gentle randomness to signals",
  },
  {
    schema: 1,
    id: "source/github",
    label: "GitHub",
    category: "identity",
    role: "source",
    colorAccent: "#6E5494",
    capabilities: ["github"],
    registers: [],
    topics: { publish: ["github/activity"], subscribe: [] },
    description: "Software activity from GitHub",
  },
  {
    schema: 1,
    id: "control/dial",
    label: "Dial",
    category: "control",
    role: "transform",
    colorAccent: "#F4A261",
    capabilities: ["analog-input"],
    registers: [
      { name: "position", offset: 16, type: "uint16", scale: 0.001 },
    ],
    topics: { publish: ["control/dial"], subscribe: [] },
    description: "Select which weather field appears on the display, or scale light",
  },
  {
    schema: 1,
    id: "transform/split",
    label: "Split",
    category: "identity",
    role: "transform",
    colorAccent: "#2A9D8F",
    capabilities: ["split"],
    registers: [],
    topics: { publish: [], subscribe: [] },
    description: "Split weather into place, temperature, and rain — one clause per display when available",
  },
  {
    schema: 1,
    id: "control/button",
    label: "Button",
    category: "control",
    role: "control",
    colorAccent: "#E76F51",
    capabilities: ["digital-input"],
    registers: [{ name: "pressed", offset: 16, type: "uint8" }],
    topics: { publish: ["control/button/press"], subscribe: [] },
    description: "Toggle contact — OPEN or CLOSED; drives outputs downstream",
  },
  {
    schema: 1,
    id: "control/slider",
    label: "Slider",
    category: "control",
    role: "control",
    colorAccent: "#2A9D8F",
    capabilities: ["analog-input"],
    registers: [
      { name: "position", offset: 16, type: "uint16", scale: 0.001 },
    ],
    topics: { publish: ["control/slider"], subscribe: [] },
    description: "Slide to modulate signals",
  },
  {
    schema: 1,
    id: "sensor/motion",
    label: "Motion",
    category: "sensor",
    role: "sensor",
    colorAccent: "#E9C46A",
    capabilities: ["pir"],
    registers: [{ name: "detected", offset: 16, type: "uint8" }],
    topics: { publish: ["sensor/motion"], subscribe: [] },
    description: "Detect movement in the room",
  },
  {
    schema: 1,
    id: "sensor/temperature",
    label: "Temperature",
    category: "sensor",
    role: "sensor",
    colorAccent: "#06D6A0",
    capabilities: ["temp"],
    registers: [{ name: "celsius", offset: 16, type: "int16", scale: 0.1 }],
    topics: { publish: ["sensor/temp"], subscribe: [] },
    description: "Ambient temperature reading",
  },
  {
    schema: 1,
    id: "output/light",
    label: "Light",
    category: "output",
    role: "output",
    colorAccent: "#FFD166",
    capabilities: ["pwm-led"],
    registers: [{ name: "brightness", offset: 16, type: "uint16", scale: 0.001 }],
    topics: { publish: [], subscribe: ["output/light/brightness"] },
    description: "Warm ambient light output",
    outputModality: "visual",
  },
  {
    schema: 1,
    id: "output/music",
    label: "Music",
    category: "output",
    role: "output",
    colorAccent: "#EF476F",
    capabilities: ["midi"],
    registers: [],
    topics: {
      publish: [],
      subscribe: ["output/music/note", "output/music/velocity"],
    },
    description: "Generative audio output",
    outputModality: "audio",
  },
  {
    schema: 1,
    id: "output/lcd",
    label: "LCD",
    category: "output",
    role: "output",
    colorAccent: "#06D6A0",
    capabilities: ["lcd"],
    registers: [],
    topics: { publish: [], subscribe: ["output/lcd/text"] },
    description: "Backlit character LCD",
    outputModality: "visual",
  },
  {
    schema: 1,
    id: "output/chime",
    label: "Chime",
    category: "output",
    role: "output",
    colorAccent: "#8338EC",
    capabilities: ["piezo"],
    registers: [{ name: "trigger", offset: 16, type: "uint8" }],
    topics: { publish: [], subscribe: ["output/chime/trigger"] },
    description: "Soft bell on trigger",
    outputModality: "audio",
  },
  {
    schema: 1,
    id: "core/core",
    label: "Core",
    category: "core",
    role: "core",
    colorAccent: "#1D3557",
    capabilities: ["wifi", "runtime"],
    registers: [],
    topics: { publish: [], subscribe: [] },
    description: "Brain of the chain — WiFi, power, runtime",
  },
];

export const PRESET_CHAINS: PresetChain[] = [
  {
    id: "london-weather-light",
    name: "London Weather Light",
    description: "Calm ambient light driven by London weather",
    cubes: ["identity/london", "identity/weather", "output/light", "core/core"],
  },
  {
    id: "weather-dial-light",
    name: "Weather Dial Light",
    description: "Dial scales how strongly weather affects light",
    cubes: [
      "identity/london",
      "identity/weather",
      "control/dial",
      "output/light",
      "core/core",
    ],
  },
  {
    id: "london-weather-calm-light",
    name: "London Weather Calm Light",
    description: "Smoothed weather as gentle ambient light",
    cubes: [
      "identity/london",
      "identity/weather",
      "modifier/calm",
      "output/light",
      "core/core",
    ],
  },
  {
    id: "room-motion-chime",
    name: "Room Motion Chime",
    description: "Motion in the room triggers a soft chime",
    cubes: ["sensor/motion", "output/chime", "core/core"],
  },
  {
    id: "rain-motion-chime",
    name: "Rain Motion Chime",
    description: "Chime when motion happens while it's raining",
    cubes: [
      "identity/london",
      "identity/weather",
      "sensor/motion",
      "output/chime",
      "core/core",
    ],
  },
  {
    id: "github-activity",
    name: "GitHub Activity",
    description: "Software activity as ambient light",
    cubes: ["source/github", "output/light", "core/core"],
  },
  {
    id: "tokyo-weather-music",
    name: "Tokyo Weather Music",
    description: "Tokyo weather as generative music",
    cubes: [
      "identity/tokyo",
      "identity/weather",
      "output/music",
      "core/core",
    ],
  },
  {
    id: "time-calm-light",
    name: "Time Calm Light",
    description: "Time of day as calm ambient light",
    cubes: ["source/time", "modifier/calm", "output/light", "core/core"],
  },
  {
    id: "button-chime",
    name: "Button Chime",
    description: "Press the button to chime",
    cubes: ["control/button", "output/chime", "core/core"],
  },
  {
    id: "github-lcd",
    name: "GitHub LCD",
    description: "GitHub activity on backlit LCD",
    cubes: ["source/github", "output/lcd", "core/core"],
  },
  {
    id: "temperature-light",
    name: "Temperature Light",
    description: "Room temperature drives light warmth",
    cubes: ["sensor/temperature", "output/light", "core/core"],
  },
  {
    id: "time-lcd",
    name: "Time LCD",
    description: "Time of day on backlit LCD",
    cubes: ["source/time", "output/lcd", "core/core"],
  },
  {
    id: "temperature-lcd",
    name: "Temperature LCD",
    description: "Room temperature on backlit LCD",
    cubes: ["sensor/temperature", "output/lcd", "core/core"],
  },
  {
    id: "weather-lcd",
    name: "Weather LCD",
    description: "London weather on backlit LCD",
    cubes: [
      "identity/london",
      "identity/weather",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "dual-city-time-lcd",
    name: "World Clock LCD",
    description: "Local time in London and Tokyo on backlit LCD",
    cubes: [
      "identity/london",
      "identity/tokyo",
      "source/time",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "dual-city-lcd",
    name: "Dual City LCD",
    description: "Tokyo time on LCD1, London weather on LCD2",
    cubes: [
      "identity/tokyo",
      "source/time",
      "output/lcd",
      "identity/london",
      "identity/weather",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "weather-moods",
    name: "Weather Moods",
    description: "Weather as ambient colour — blue for rain, yellow when dry",
    cubes: [
      "identity/london",
      "identity/weather",
      "output/light",
      "core/core",
    ],
  },
  {
    id: "weather-dial-lcd",
    name: "Weather Dial LCD",
    description: "Dial selects temperature, rain, or full weather on LCD",
    cubes: [
      "identity/london",
      "identity/weather",
      "control/dial",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "split-weather-dual-lcd",
    name: "Split Weather LCD",
    description: "Temperature on LCD1, rain on LCD2",
    cubes: [
      "identity/london",
      "identity/weather",
      "transform/split",
      "output/lcd",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "presence-weather-lcd",
    name: "Presence Weather",
    description: "London weather on LCD only when motion is detected",
    cubes: [
      "sensor/motion",
      "identity/london",
      "identity/weather",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "activity-desk",
    name: "Activity Desk",
    description: "Foundry commit count on LCD",
    cubes: [
      "identity/foundry",
      "source/github",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "world-desk",
    name: "World Desk",
    description: "Tokyo time, London weather, GitHub activity light — three sentences at once",
    cubes: [
      "identity/tokyo",
      "source/time",
      "output/lcd",
      "identity/london",
      "identity/weather",
      "output/lcd",
      "source/github",
      "output/light",
      "core/core",
    ],
  },
];

/** Starter kit cubes for delight validation and first hardware SKU. */
export const STARTER_CUBE_IDS = new Set([
  "identity/london",
  "identity/weather",
  "control/dial",
  "output/light",
  "sensor/motion",
  "output/chime",
  "core/core",
]);

/** Hero presets shown by default in product mode. */
export const HERO_PRESET_IDS = [
  "weather-moods",
  "weather-dial-lcd",
  "world-desk",
  "split-weather-dual-lcd",
  "room-motion-chime",
] as const;

export function getCubeDefinition(id: string): CubeDefinition | undefined {
  return CUBE_DEFINITIONS.find((c) => c.id === id);
}

export function getCubesByCategory(
  category: CubeDefinition["category"],
): CubeDefinition[] {
  return CUBE_DEFINITIONS.filter((c) => c.category === category);
}

export function getOutputModality(definitionId: string): OutputModality | undefined {
  return getCubeDefinition(definitionId)?.outputModality;
}

export function isAudioOutput(definitionId: string): boolean {
  return getOutputModality(definitionId) === "audio";
}

export function isVisualOutput(definitionId: string): boolean {
  return getOutputModality(definitionId) === "visual";
}
