import type { CubeDefinition, PresetChain } from "./schema.js";

export const CUBE_DEFINITIONS: CubeDefinition[] = [
  {
    schema: 1,
    id: "identity/london",
    label: "London",
    category: "identity",
    role: "place",
    colorAccent: "#E63946",
    capabilities: ["place"],
    metadata: { lat: 51.5074, lon: -0.1278, city: "London", timezone: "Europe/London" },
    registers: [],
    topics: { publish: ["place/name"], subscribe: [] },
    description: "Use weather and data for London, UK",
  },
  {
    schema: 1,
    id: "identity/tokyo",
    label: "Tokyo",
    category: "identity",
    role: "place",
    colorAccent: "#FF6B6B",
    capabilities: ["place"],
    metadata: { lat: 35.6762, lon: 139.6503, city: "Tokyo", timezone: "Asia/Tokyo" },
    registers: [],
    topics: { publish: ["place/name"], subscribe: [] },
    description: "Use weather and data for Tokyo, Japan",
  },
  {
    schema: 1,
    id: "identity/weather",
    label: "Weather",
    category: "identity",
    role: "source",
    colorAccent: "#457B9D",
    capabilities: ["weather"],
    registers: [],
    topics: { publish: ["weather/temp", "weather/rain"], subscribe: [] },
    description: "Fetch temperature and rain from the sky",
  },
  {
    schema: 1,
    id: "source/time",
    label: "Time",
    category: "identity",
    role: "source",
    colorAccent: "#5C6BC0",
    capabilities: ["time"],
    registers: [],
    topics: { publish: ["time/hour"], subscribe: [] },
    description: "Time of day as a signal",
  },
  {
    schema: 1,
    id: "modifier/calm",
    label: "Calm",
    category: "identity",
    role: "modifier",
    colorAccent: "#2A9D8F",
    capabilities: ["smooth"],
    registers: [],
    topics: {
      publish: ["weather/rain/smoothed"],
      subscribe: ["weather/rain"],
    },
    description: "Smooth signals for gentle ambient output",
  },
  {
    schema: 1,
    id: "modifier/random",
    label: "Random",
    category: "identity",
    role: "modifier",
    colorAccent: "#9B59B6",
    capabilities: ["random"],
    registers: [],
    topics: { publish: ["modifier/random"], subscribe: [] },
    description: "Add gentle randomness to signals",
  },
  {
    schema: 1,
    id: "source/github",
    label: "GitHub",
    category: "identity",
    role: "source",
    colorAccent: "#6E5494",
    capabilities: ["github"],
    registers: [],
    topics: { publish: ["github/activity"], subscribe: [] },
    description: "Software activity from GitHub",
  },
  {
    schema: 1,
    id: "control/dial",
    label: "Dial",
    category: "control",
    role: "control",
    colorAccent: "#F4A261",
    capabilities: ["analog-input"],
    registers: [
      { name: "position", offset: 16, type: "uint16", scale: 0.001 },
    ],
    topics: { publish: ["control/dial"], subscribe: [] },
    description: "Turn to scale or modulate signals",
  },
  {
    schema: 1,
    id: "control/button",
    label: "Button",
    category: "control",
    role: "control",
    colorAccent: "#E76F51",
    capabilities: ["digital-input"],
    registers: [{ name: "pressed", offset: 16, type: "uint8" }],
    topics: { publish: ["control/button/press"], subscribe: [] },
    description: "Press to trigger events",
  },
  {
    schema: 1,
    id: "control/slider",
    label: "Slider",
    category: "control",
    role: "control",
    colorAccent: "#2A9D8F",
    capabilities: ["analog-input"],
    registers: [
      { name: "position", offset: 16, type: "uint16", scale: 0.001 },
    ],
    topics: { publish: ["control/slider"], subscribe: [] },
    description: "Slide to modulate signals",
  },
  {
    schema: 1,
    id: "sensor/motion",
    label: "Motion",
    category: "sensor",
    role: "sensor",
    colorAccent: "#E9C46A",
    capabilities: ["pir"],
    registers: [{ name: "detected", offset: 16, type: "uint8" }],
    topics: { publish: ["sensor/motion"], subscribe: [] },
    description: "Detect movement in the room",
  },
  {
    schema: 1,
    id: "sensor/temperature",
    label: "Temperature",
    category: "sensor",
    role: "sensor",
    colorAccent: "#06D6A0",
    capabilities: ["temp"],
    registers: [{ name: "celsius", offset: 16, type: "int16", scale: 0.1 }],
    topics: { publish: ["sensor/temp"], subscribe: [] },
    description: "Ambient temperature reading",
  },
  {
    schema: 1,
    id: "output/light",
    label: "Light",
    category: "output",
    role: "output",
    colorAccent: "#FFD166",
    capabilities: ["pwm-led"],
    registers: [{ name: "brightness", offset: 16, type: "uint16", scale: 0.001 }],
    topics: { publish: [], subscribe: ["output/light/brightness"] },
    description: "Warm ambient light output",
  },
  {
    schema: 1,
    id: "output/music",
    label: "Music",
    category: "output",
    role: "output",
    colorAccent: "#EF476F",
    capabilities: ["midi"],
    registers: [],
    topics: {
      publish: [],
      subscribe: ["output/music/note", "output/music/velocity"],
    },
    description: "Generative MIDI output",
  },
  {
    schema: 1,
    id: "output/display",
    label: "Display",
    category: "output",
    role: "output",
    colorAccent: "#118AB2",
    capabilities: ["eink"],
    registers: [],
    topics: { publish: [], subscribe: ["output/display/text"] },
    description: "Low-power e-ink text display",
  },
  {
    schema: 1,
    id: "output/lcd",
    label: "LCD",
    category: "output",
    role: "output",
    colorAccent: "#06D6A0",
    capabilities: ["lcd"],
    registers: [],
    topics: { publish: [], subscribe: ["output/lcd/text"] },
    description: "Backlit character LCD",
  },
  {
    schema: 1,
    id: "output/chime",
    label: "Chime",
    category: "output",
    role: "output",
    colorAccent: "#8338EC",
    capabilities: ["piezo"],
    registers: [{ name: "trigger", offset: 16, type: "uint8" }],
    topics: { publish: [], subscribe: ["output/chime/trigger"] },
    description: "Soft bell on trigger",
  },
  {
    schema: 1,
    id: "core/core",
    label: "Core",
    category: "core",
    role: "core",
    colorAccent: "#1D3557",
    capabilities: ["wifi", "runtime"],
    registers: [],
    topics: { publish: [], subscribe: [] },
    description: "Brain of the chain — WiFi, power, runtime",
  },
];

export const PRESET_CHAINS: PresetChain[] = [
  {
    id: "london-weather-light",
    name: "London Weather Light",
    description: "Calm ambient light driven by London weather",
    cubes: ["identity/london", "identity/weather", "output/light", "core/core"],
  },
  {
    id: "weather-dial-light",
    name: "Weather Dial Light",
    description: "Dial scales how strongly weather affects light",
    cubes: [
      "identity/london",
      "identity/weather",
      "control/dial",
      "output/light",
      "core/core",
    ],
  },
  {
    id: "london-weather-calm-light",
    name: "London Weather Calm Light",
    description: "Smoothed weather as gentle ambient light",
    cubes: [
      "identity/london",
      "identity/weather",
      "modifier/calm",
      "output/light",
      "core/core",
    ],
  },
  {
    id: "room-motion-chime",
    name: "Room Motion Chime",
    description: "Motion in the room triggers a soft chime",
    cubes: ["sensor/motion", "output/chime", "core/core"],
  },
  {
    id: "github-activity",
    name: "GitHub Activity",
    description: "Software activity as ambient light",
    cubes: ["source/github", "output/light", "core/core"],
  },
  {
    id: "tokyo-weather-music",
    name: "Tokyo Weather Music",
    description: "Tokyo weather as generative music",
    cubes: [
      "identity/tokyo",
      "identity/weather",
      "output/music",
      "core/core",
    ],
  },
  {
    id: "time-calm-light",
    name: "Time Calm Light",
    description: "Time of day as calm ambient light",
    cubes: ["source/time", "modifier/calm", "output/light", "core/core"],
  },
  {
    id: "button-chime",
    name: "Button Chime",
    description: "Press the button to chime",
    cubes: ["control/button", "output/chime", "core/core"],
  },
  {
    id: "github-display",
    name: "GitHub Display",
    description: "GitHub activity on e-ink display",
    cubes: ["source/github", "output/display", "core/core"],
  },
  {
    id: "temperature-light",
    name: "Temperature Light",
    description: "Room temperature drives light warmth",
    cubes: ["sensor/temperature", "output/light", "core/core"],
  },
  {
    id: "time-lcd",
    name: "Time LCD",
    description: "Time of day on backlit LCD",
    cubes: ["source/time", "output/lcd", "core/core"],
  },
  {
    id: "temperature-lcd",
    name: "Temperature LCD",
    description: "Room temperature on backlit LCD",
    cubes: ["sensor/temperature", "output/lcd", "core/core"],
  },
  {
    id: "weather-lcd",
    name: "Weather LCD",
    description: "London weather on backlit LCD",
    cubes: [
      "identity/london",
      "identity/weather",
      "output/lcd",
      "core/core",
    ],
  },
  {
    id: "dual-city-time-lcd",
    name: "World Clock LCD",
    description: "Local time in London and Tokyo on backlit LCD",
    cubes: [
      "identity/london",
      "identity/tokyo",
      "source/time",
      "output/lcd",
      "core/core",
    ],
  },
];

/** Starter kit cubes for delight validation and first hardware SKU. */
export const STARTER_CUBE_IDS = new Set([
  "identity/london",
  "identity/weather",
  "control/dial",
  "output/light",
  "sensor/motion",
  "output/chime",
  "core/core",
]);

/** Hero presets shown by default in product mode. */
export const HERO_PRESET_IDS = [
  "weather-dial-light",
  "london-weather-light",
  "room-motion-chime",
] as const;

export function getCubeDefinition(id: string): CubeDefinition | undefined {
  return CUBE_DEFINITIONS.find((c) => c.id === id);
}

export function getCubesByCategory(
  category: CubeDefinition["category"],
): CubeDefinition[] {
  return CUBE_DEFINITIONS.filter((c) => c.category === category);
}
